<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'description',
        'image',
        'price'
    ];
    public function save(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
