name: Merge to Main Workflow

on:
  workflow_run:
    workflows: ["Laravel Sail CI"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check Workflow Status
        id: check_workflow
        run: echo "::set-output name=success::$(echo ${{ github.event.workflow_run.conclusion }} == 'success')"

      - name: Merge to Main
        if: steps.check_workflow.outputs.success == 'true'
        run: |
          echo "Merging to main..."
          git checkout main
          git merge dev --no-ff
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
