name: Laravel

on:
  push:
    branches: [ "Task_4.5" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: start sail
        run: ./vendor/bin/sail up -d
      - name: Copy .env
        run: cp .env.example .env
      - name: Generate key
        run: ./vendor/bin/sail artisan key:generate
      - name: Update DB_HOST in .env
        working-directory: ./product-catalog
        run: |
          container_name="shopx-mysql-1"
          container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_name)
          sed -i "s/^DB_HOST=.*/DB_HOST=$container_ip/" .env
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: shopx
          DB_USERNAME: sail
          DB_PASSWORD: password
        run: ./vendor/bin/sail artisan test
