name: Build Workflow

on:
  push:
    branches:
      - Task_4.5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install

      - name: Copy .env
        run: |
          cp .env.example .env

      - name: Stop and Remove Sail Containers
        run: ./vendor/bin/sail down -v

      - name: Start Laravel Sail
        run: |
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan key:generate

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/sail artisan test

      - name: Deploy to server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd shopx
            git pull
            npm ci
            npm run build
            composer i
            php artisan migrate --force
