name: Deploy1

on:
  push:
    branches: [Task_4.5]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Copy .env
        run: cp .env.example .env
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup project
        run: |
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan config:clear
          ./vendor/bin/sail artisan cache:clear
          ./vendor/bin/sail artisan key:generate
      - name: Directory permissions
        run: chmod 777 -R .
      - name: Run Unit tests
        run: ./vendor/bin/sail artisan test
      - name: Deploy to server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd shopx
            git pull
            npm ci
            npm run build
            composer i
            php artisan migrate --force
