name: Merge to Main Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check Conditions
        run: |
            git checkout main
            git merge --no-ff dev -m "Merge dev into main"
            git push origin main
