name: Merge to Main Workflow

on:
  workflow_run:
    workflows: ["Laravel Sail CI"]
    types:
      - completed

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Conditions
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if [ "${{ github.event.pull_request.state }}" == "closed" ]; then
            git checkout main
            git merge --no-ff dev -m "Merge dev into main"
            git push origin main
          else
            sleep 20
            fi
          fi
