name: Merge to Main Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Conditions
        run: |
            git fetch origin
            git checkout main
            git merge origin/dev --no-ff --no-edit
            git push origin main
