name: Merge to Main Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  merge-to-main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'Task_4.7'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'dev'
          fetch-depth: 0

      - name: Merge to main
        run: |
          git checkout main
          git merge --no-ff dev
          git push origin main
